# Generated by Django 5.0.6 on 2024-05-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Restaurant"), (2, "Customer")],
                default=1,
                null=True,
            ),
        ),
    ]
