# Generated by Django 5.0.6 on 2024-06-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_alter_fooditem_food_name_alter_fooditem_slug"),
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fooditem",
            options={
                "ordering": ["food_name"],
                "verbose_name": "food item",
                "verbose_name_plural": "food items",
            },
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("vendor", "category_name")},
        ),
        migrations.AlterUniqueTogether(
            name="fooditem",
            unique_together={("vendor", "category", "food_name")},
        ),
    ]
