# Generated by Django 5.0.6 on 2024-06-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="pin_code",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
