# Generated by Django 5.0.6 on 2024-07-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_pin_code"),
        ("vendor", "0006_alter_openinghours_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="vendors",
            field=models.ManyToManyField(blank=True, to="vendor.vendor"),
        ),
    ]
